[versions]
agp = "9.0.1"
material = "1.13.0"

[libraries]
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }